"""Core domain models for the Git subsystem."""

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path


class ChangeType(str, Enum):
    """Types of Git changes."""

    ADDED = "ADDED"
    MODIFIED = "MODIFIED"
    DELETED = "DELETED"
    RENAMED = "RENAMED"
    UNTRACKED = "UNTRACKED"
    UNKNOWN = "UNKNOWN"


@dataclass
class GitBranch:
    """Represents a Git branch."""

    name: str
    is_current: bool
    is_remote: bool


@dataclass
class GitChange:
    """Represents a file change in Git."""

    path: str
    change_type: ChangeType
    staged: bool


@dataclass
class GitStatus:
    """Represents the status of a Git repository."""

    branch: str
    is_clean: bool
    staged_changes: list[GitChange] = field(default_factory=list)
    unstaged_changes: list[GitChange] = field(default_factory=list)
    untracked_changes: list[GitChange] = field(default_factory=list)


@dataclass
class GitDiff:
    """Represents a diff generated by Git."""

    changed_files: int
    insertions: int
    deletions: int
    patch: str
    truncated: bool = False


@dataclass
class GitCommit:
    """Represents a created Git commit."""

    commit_hash: str
    message: str
    branch: str


@dataclass
class Workspace:
    """Represents a managed task workspace."""

    task_id: str
    root_path: Path
    branch: str
    repository_path: Path


@dataclass
class WorkspaceCheckpoint:
    """Represents a safe point to rollback to.

    A WorkspaceCheckpoint represents a CLEAN COMMITTED repository state.
    It does NOT represent arbitrary working-tree changes, staged changes,
    or untracked files.
    """

    task_id: str
    branch: str
    commit_hash: str
    status: GitStatus
