"""Domain models for LLM interactions."""

from typing import Any, Literal

from pydantic import BaseModel, Field


class LLMToolCall(BaseModel):
    """A tool call requested by the LLM."""

    id: str
    name: str
    arguments: dict[str, Any]


class LLMMessage(BaseModel):
    """A message in an LLM conversation."""

    role: Literal["system", "user", "assistant", "tool"]
    content: str | None = None
    tool_calls: list[LLMToolCall] | None = None
    tool_call_id: str | None = None


class LLMRequest(BaseModel):
    """A request to generate text from an LLM."""

    model: str
    messages: list[LLMMessage]
    temperature: float | None = Field(default=None, ge=0.0, le=2.0)
    max_tokens: int | None = Field(default=None, gt=0)
    tools: list[dict[str, Any]] = Field(default_factory=list)


class LLMUsage(BaseModel):
    """Token usage statistics for an LLM response."""

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0


class LLMResponse(BaseModel):
    """A response generated by an LLM."""

    content: str | None = None
    model: str
    usage: LLMUsage = Field(default_factory=LLMUsage)
    finish_reason: str | None = None
    request_id: str | None = None
    tool_calls: list[LLMToolCall] | None = None
